# User Test
#------------------------------------

APP              = test
APP_SRCS        += gpio.c
APP_INC	        +=
APP_CFLAGS      +=

PLPBRIDGE_FLAGS += -f BUILD/GAP8_V2/GCC_RISCV/test

include $(RULES_DIR)/pmsis_rules.mk
